version: "3.2"
services:
  php:
    build: 
      context: .
    image: dennyfardian/denny
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DB=dbtodolist
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:80"
    container_name: to-do-list
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=root
      - MYSQL_PASSWORD= 
      - MYSQL_DATABASE=dbtodolist
    container_name: to-do-list-mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=to-do-list
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: to-do-list-phpmyadmin
networks:
  frontend:
  backend: